{% set version = "1.7.0" %}

package:
  name: libcst
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/libcst/libcst-{{ version }}.tar.gz
  sha256: a63f44ffa81292f183656234c7f2848653ff45c17d867db83c9335119e28aafa
  patches:
    - 0001-Add-headerpad_max_install_names-to-linker-arguments.patch

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cd native/libcst && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - setuptools-rust                        # [build_platform != target_platform]
    - setuptools_scm                         # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - setuptools
    - setuptools-rust
    - setuptools_scm
  run:
    - python
    - pyyaml >=5.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - libcst
    - libcst._nodes
    - libcst._nodes.tests
    - libcst._parser
    - libcst._parser.conversions
    - libcst._parser.parso
    - libcst._parser.parso.pgen2
    - libcst._parser.parso.python
    - libcst._parser.parso.tests
    - libcst._parser.tests
    - libcst._parser.types
    - libcst._parser.types.tests
    - libcst.codegen
    - libcst.codegen.tests
    - libcst.codemod
    - libcst.codemod.commands
    - libcst.codemod.commands.tests
    - libcst.codemod.tests
    - libcst.codemod.visitors
    - libcst.codemod.visitors.tests
    - libcst.helpers
    - libcst.helpers.tests
    - libcst.matchers
    - libcst.matchers.tests
    - libcst.metadata
    - libcst.metadata.tests
    - libcst.testing
    - libcst.tests

about:
  home: https://github.com/Instagram/LibCST
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - native/libcst/THIRDPARTY.yml
  summary: A concrete syntax tree with AST-like properties for Python 3.0 through 3.13 programs.
  doc_url: https://libcst.readthedocs.io/
  dev_url: https://github.com/Instagram/LibCST

extra:
  recipe-maintainers:
    - nehaljwani
    - bollwyvl
    - xylar
