# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.8.1"

package:
  name: libcst
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/libcst/libcst-${{ version }}.tar.gz
  sha256: 423427819409a1d905017bbd51062bd0f1e4795c74c2f9f52a6b63dd67c282d2
  patches:
    - 0001-Add-headerpad_max_install_names-to-linker-arguments.patch

build:
  number: 0
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      - cd native/libcst
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools
        - setuptools-rust
        - setuptools-scm
  host:
    - python
    - pip
    - setuptools
    - setuptools-rust
    - setuptools-scm
  run:
    - python
    - if: match(python, ">=3.13")
      then: pyyaml-ft >=8.0.0
      else: pyyaml >=5.2
    - if: match(python, "<3.10")
      then: typing_extensions

tests:
  - python:
      imports:
        - libcst
        - libcst._nodes
        - libcst._nodes.tests
        - libcst._parser
        - libcst._parser.conversions
        - libcst._parser.parso
        - libcst._parser.parso.pgen2
        - libcst._parser.parso.python
        - libcst._parser.parso.tests
        - libcst._parser.tests
        - libcst._parser.types
        - libcst._parser.types.tests
        - libcst.codegen
        - libcst.codegen.tests
        - libcst.codemod
        - libcst.codemod.commands
        - libcst.codemod.commands.tests
        - libcst.codemod.tests
        - libcst.codemod.visitors
        - libcst.codemod.visitors.tests
        - libcst.helpers
        - libcst.helpers.tests
        - libcst.matchers
        - libcst.matchers.tests
        - libcst.metadata
        - libcst.metadata.tests
        - libcst.testing
        - libcst.tests

about:
  license: MIT
  license_file:
    - LICENSE
    - native/libcst/THIRDPARTY.yml
  summary: A concrete syntax tree with AST-like properties for Python 3.0 through 3.13 programs.
  homepage: https://github.com/Instagram/LibCST
  documentation: https://libcst.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani
    - bollwyvl
    - xylar
